# Generated by Django 5.0.7 on 2024-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('acoes', models.TextField()),
            ],
        ),
    ]
